/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library 
{
    public int addint(int a,int b) 
    {
    	int result = a+b;
    	return result;
    }

    public int substractint(int a,int b) 
    {
    	int result = a-b;
    	return result;
    }

}
