/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import static org.junit.Assert.*;
import static org.junit.Assume.assumeTrue;

import org.apache.commons.math3.distribution.WeibullDistribution;
import org.apache.http.util.Asserts;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;

public class LibraryTest {
	
	WebDriver driver;
	
	@Before
	public void openBrowser() {
		driver = new ChromeDriver();
	}
	
	@Test 
    public void ChromeTest() 
    {
		driver.get("https://en.wikipedia.org");
		WebElement barreRecherche = driver.findElement(By.id("searchInput"));
		barreRecherche.sendKeys("World Cup");
		
		WebElement button = driver.findElement(By.id("searchButton"));
		button.click();
		
		WebElement link = driver.findElement(By.xpath("//*[@id=\"mw-content-text\"]/div/p[1]/a"));
		link.click();
		
		
		WebElement title = driver.findElement(By.id("firstHeading"));
		
		/*
		boolean test;
		test = (title.getText() == ("FIFA World Cup"));
		*/
		
		Assert.assertEquals("FIFA World Cup", title.getText());
		
		System.out.println(title.getText());
		
		try {
			Thread.sleep(10000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		driver.quit();
    }
	
	@After
	public void quit() {
		driver.quit();
	}

}
